# Generated by Django 5.2.4 on 2025-07-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('customer_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('type', models.CharField(max_length=10)),
            ],
        ),
    ]
